# Generated by Django 4.0 on 2022-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_excel', '0002_alter_mis_engine_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='parts_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistical_year', models.CharField(blank=True, max_length=32, null=True, verbose_name='统计月')),
                ('parts', models.CharField(blank=True, max_length=64, null=True, verbose_name='零部件')),
                ('mis_3', models.CharField(blank=True, max_length=32, null=True, verbose_name='3mis')),
                ('mis_6', models.CharField(blank=True, max_length=32, null=True, verbose_name='6mis')),
                ('mis_9', models.CharField(blank=True, max_length=32, null=True, verbose_name='9mis')),
                ('mis_12', models.CharField(blank=True, max_length=32, null=True, verbose_name='12mis')),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='类型')),
                ('engine_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='发动机平台')),
                ('let', models.CharField(blank=True, max_length=32, null=True, verbose_name='排放')),
                ('purpose', models.CharField(blank=True, max_length=32, null=True, verbose_name='用途')),
            ],
        ),
        migrations.RenameModel(
            old_name='Mis',
            new_name='sale_data',
        ),
    ]
