# Generated by Django 4.0 on 2022-11-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_excel', '0005_claim_data_test_delete_claim_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='claim_data_test',
        ),
    ]
